### ISSUE TITLE
SFPNOP is not issued after required instructions in certain cases.

### ISSUE THREAD

**Issue by amahmudTT** [tenstorrent/sfpi#13]
The compiler is not issuing `SFPNOP` instructions at least after `SFPMUL` instructions in certain scenarios even when they are needed. 

**Example scenario :**

Architecture : wormhole_b0
OS : Ubuntu 20.04.6 LTS

When the power_tile function is called it eventually calls calculate_power_iterative which gets inlined. The  function has a 2 level loop. The outer loop gets unrolled. 

```
template <bool APPROXIMATION_MODE,int ITERATIONS = 8>
inline void calculate_power_iterative(const uint exponent)
{
    #pragma GCC unroll 8
    for (int d = 0; d < 8; d++)
    {
        vFloat in = dst_reg[0];
        vFloat result = 1.0f;
        for (uint i = 0; i < exponent; i++) {
            result *= in;
            // TTI_SFPNOP;
        }
            dst_reg[0]=result;
        dst_reg++;
    }
}
```

When the power_tile function is itself called within a loop, during the unrolling and inlining `SFPNOP` instructions are not issued after `SFPMUL`  instruction in the last 5 out of the total 8 unrolled instances leading to wrong result.

```
    7834:	00ee0863          	beq	t3, a4, 7844 <kernel_launch()+0x38c>
    7838:	18006402          	sfpmul	L0, L0, L1, L9, 0
    783c:	00170713          	addi	a4, a4, 1
    7840:	ff5ff06f          	j	7834 <kernel_launch()+0x37c>
    7844:	c8030001          	sfpstore	0, L0, 0, 3
```

**How to reproduce:**

Architecture : wormhole_b0
OS : Ubuntu 20.04.6 LTS

In the branch 
`https://github.com/tenstorrent/tt-metal/tree/amahmud/power_debug,`  
running the python test
`pytest ./tests/tt_eager/python_api_testing/unit_testing/misc/test_moreh_norm.py` 
will compile the kernel `./ttnn/cpp/ttnn/deprecated/tt_dnn/op_library/moreh_norm/moreh_norm_h/kernels/moreh_norm_h_kernel.cpp`

This kernel calls power_tile within a loop that will run only once and produces redundant values in the place of padded zeroes of the output tensor due to the mentioned issue. You can see the missing `SFPNOPS` by generating assembly code for the file in 
`/tt-metal/built/<generated-number>/kernels/moreh_norm_h_kernel/<generated-number>/trisc1/trisc1.elf `

In my branch I have already generated and dumped the assembly code and elf files in the folder `/tt-metal/assembly/ `with appropriate names

The code in the `moreh_norm_h_kernel.cpp` will call `power_tile` within a loop, but if you comment that part and uncomment the code above which does the same thing but not being within a loop, the issue will not be encountered. 

```
void MAIN {
      
    // OMITTED CODE  

/*
    // **The following code produces the correct output.**
    
    // DPRINT_PACK( DPRINT << "EXECUTE POWER \n";)
    ACQ();
    cb_wait_front(cb_x, onetile);
    cb_reserve_back(cb_y, onetile);

    // copy
    copy_tile_init();
    copy_tile(cb_x, 0, dst0);

    // power
    power_tile_init();
    power_tile(dst0, p);

    pack_tile(dst0, cb_y);

    cb_push_back(cb_y, onetile);

    cb_pop_front(cb_x, onetile);
    REL();
*/
    
    **// The loop below runs only once, but unlike the code above will miss issuing SFPNOPs
    // In the correct places.** 
    
    // DPRINT_PACK(DPRINT << "num_cols_per_core " << num_cols_per_core << "\n"; )
    // DPRINT_PACK(DPRINT << "Ht " << Ht << "\n"; )
    // This loop only runs once.
    for (uint32_t col_idx = 0; col_idx < num_cols_per_core; ++col_idx) {
        // This loop only runs once.
        for (uint32_t row_idx = 0; row_idx < Ht; ++row_idx) {
            // DPRINT_PACK( DPRINT << "EXECUTE POWER \n";)
            // The following code is identical to the above but produces incorrect output.
            ACQ();
            cb_wait_front(cb_x, onetile);
            cb_reserve_back(cb_y, onetile);

            // copy
            copy_tile_init();
            copy_tile(cb_x, 0, dst0);

            // power
            power_tile_init();
            power_tile(dst0, p);

            pack_tile(dst0, cb_y);
            cb_push_back(cb_y, onetile);

            cb_pop_front(cb_x, onetile);
            REL();
        }
    }
}  // void MAIN
}

```
Without loop (gives correct result and has SFPNOP after every SFPMUL)
[power_no_loop_correct.txt](https://github.com/user-attachments/files/16641712/power_no_loop_correct.txt)

With loop (does not have SFPNOP after 5 instances of SFPMUL)
[power_loop_bug_asm.txt](https://github.com/user-attachments/files/16641715/power_loop_bug_asm.txt)

This issue has been identified from issue : https://github.com/tenstorrent/tt-metal/issues/7928

**Comment by nathan-TT** [comment]
Compiler sources updated. binary PR raised  https://github.com/tenstorrent/tt-metal/pull/12061

**Comment by nathan-TT** [comment]
Updated compiler merged https://github.com/tenstorrent/tt-metal/pull/12061
